# Generated by Django 3.0.7 on 2020-06-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('embed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedmodel',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='tournament.TournamentModel', verbose_name='Турнир'),
        ),
    ]
