# Generated by Django 3.0.7 on 2020-06-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embed', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('tournaments', models.ManyToManyField(related_name='participants', to='tournament.TournamentModel', verbose_name='Турниры')),
            ],
        ),
        migrations.CreateModel(
            name='UserReactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('embed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='embed.EmbedModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='user.UserModel')),
            ],
        ),
    ]
