# Generated by Django 3.0.7 on 2020-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='participants', to='tournament.TournamentModel', verbose_name='Турниры'),
        ),
    ]
