# Generated by Django 3.0.7 on 2020-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200627_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='challonge_account',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Challonge аккаунт'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='discord_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ник в дискорде'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='max_ranked',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный MMR'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='raiting_games_count',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Количество рейтинговых игр'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ranked_ftw',
            field=models.URLField(blank=True, null=True, verbose_name='Ranked_ftw'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rasa',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Раса'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sc_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ник в SC'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='team',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название команды'),
        ),
    ]
