# Generated by Django 3.0.7 on 2020-06-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_remove_scenariomodel_user'),
        ('user', '0003_auto_20200628_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.ScenarioModel', verbose_name='Активный сценарий'),
        ),
    ]
