# Generated by Django 3.0.7 on 2020-06-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='next_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='Следующий вопрос'),
        ),
    ]
