# Generated by Django 3.0.7 on 2020-06-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200628_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название сценария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField(verbose_name='Вопрос')),
                ('is_last', models.BooleanField(default=False, verbose_name='Последний вопрос?')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.ScenarioModel', verbose_name='Сценарий')),
            ],
        ),
    ]
