# Generated by Django 3.0.7 on 2020-06-28 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200628_1147'),
        ('scenario', '0002_auto_20200628_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariomodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserModel', verbose_name='Пользователь'),
        ),
    ]
